config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'welcome#index'

  get '/welcome', to: 'welcome#index', as: 'welcome_index'
  get '/favorites', to: 'favorites#show', as: 'favorites'

  delete '/favorites/:id/delete_from_favorites', to: 'favorites#destroy', as: 'delete_from_favorites'

  post '/users/:id/add_to_favorites', to: 'favorites#create', as: 'add_to_favorites'
  post '/users/:id/activate_user', to: 'users#activate', as: 'activate_user'
  post '/users/:id/ban_user', to: 'users#ban', as: 'ban_user'
  post '/users/:id/report', to: 'reports#create', as: 'report_user'
  post '/users/:id/verify_user', to: 'users#verify_user', as: 'verify_user'

  get '/users/edit_profile', to: 'users#edit', as: 'edit_profile'
  put '/users/edit_profile', to: 'users#update'
  get "/users", to: "users#index"

  get '/users/:id', to: 'users#show', as: 'user'
  delete '/users/:id', to: 'users#destroy', as: "user_delete"
  delete '/edit_profile/delete_profile', to: 'users#self_destroy', as: "user_self_destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :reports, foreign_key: :reported_user_id
  has_many :reports_sent, class_name: 'Report', foreign_key: :sender_id
  has_many :reported_users, through: :reports
  has_many :reported_by_users, through: :reports, source: :sender
  has_many :favorite_records, foreign_key: :favoriter_id, class_name: 'FavoriteUser'
  has_many :favorite_users, through: :favorite_records, source: :favorit
  has_one_attached :avatar

  acts_as_paranoid

  before_validation :set_random_password
  

  include Filterable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  enum role: [:user, :admin, :blocked, :activate]

  def have_favorite?(user)
    FavoriteUser.where(favoriter_id: id, favorit_id: user.id).any?
  end

  def self.from_google(email:, uid:)
    create_with(uid: uid).find_or_create_by!(email: email)
  end

  def active_for_authentication?
    super && !blocked?
  end
  

  filterrific(
    default_filter_params: { sorted_by: "first_name_desc"},
    available_filters: [:sorted_by, :search_query, :with_created_at_gte]
  )

  scope :search_query, ->(query) {
    return nil  if query.blank?

    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
  
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.tr("*", "%") + "%").gsub(/%+/, "%")
    }

    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conds = 2
    
    where(
      terms.map { |_term| "(LOWER(users.first_name) LIKE ? OR LOWER(users.last_name) LIKE ?)"}.join(" AND "),
      *terms.map { |e| [e] * num_or_conds }.flatten,
    )
  }

  scope :sorted_by, ->(sort_option) {
    direction = /desc$/.match?(sort_option) ? "desc" : "asc"
    case sort_option.to_s
    when /^first_name/
      order("LOWER(users.first_name) #{direction}")
    when /^email/
      order("LOWER(users.email) #{direction}")
    when /^created_at/
      order("LOWER(users.created_at) #{direction}")
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }
  scope :with_created_at_gte, ->(ref_date) {
    where("users.created_at >= ?", reference_time)
  }

  # This method provides select options for the `sorted_by` filter select input.
  # It is called in the controller as part of `initialize_filterrific`.
  def self.options_for_sorted_by
    [
      ["Name (a-z)", "first_name_asc"],
      ["Registration date (newest first)", "created_at_desc"],
      ["Registration date (oldest first)", "created_at_asc"],
    ]
  end

  private

  def set_random_password
    if self.uid.present? && self.password.nil?
      self.password = SecureRandom.urlsafe_base64
      self.password_confirmation = self.password
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = User.from_google(from_google_params)

    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end


  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  def from_google_params
    @from_google_params ||= {
      uid: auth.uid,
      email: auth.info.email
    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    def after_sign_out_path_for(_resource_or_scope)
      new_user_session_path
    end
  
    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || root_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @report = Report.new
  end

  def ban
    raise 'operation not permited' unless can? :ban, User

    @user = User.find(params[:id])
    @user.role = :blocked
    @user.save
    render 'users/show'
  end

  def activate
    raise 'operation not permited' unless can? :activate, User
    @user = User.find(params[:id])
    @user.role = :user
    @user.save
    render "users/show"
  end

  def verify_user
    raise 'operation not permited' unless can? :verify, User
    @user = User.find(params[:id])
    @user.update(verified: true)
    redirect_to user_url(@user)
  end

  def edit
  end

  def self_destroy
    current_user.destroy
    flash[:success] = "Your account deleted"
    redirect_to users_url
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def update
    if current_user.update(user_params)
      flash[:success] = "Team Member successfully Updated!"
    else
      flash[:danger] = "Team Member unsuccessfully Updated!"
    end
    render 'edit'
  end

  def index
    @filterrific = initialize_filterrific(
      User,
      params[:filterrific],
      select_options: {
        sorted_by: User.options_for_sorted_by
      },
      persistence_id: "shared_key",
      sanitize_params: true,
    ) || return

    @users = @filterrific.find.page(params[:page])

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js {render partial: 'users/index.js.erb'}
    end

  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{e.message}"
    redirect_to(reset_filterrific_url(format: :html)) && return
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.js.erb
<% js = escape_javascript(render(partial: 'users/list', locals: { users: @users })) %>
$("#filterrific_results").html("<%= js %>");

app/views/users/_list.html.erb
<div id="filterrific_results">



  <table>
    <tr>
      <th><%= filterrific_sorting_link(@filterrific, :first_name) %></th>
      <th><%= filterrific_sorting_link(@filterrific, :email) %></th>
      <th><%= filterrific_sorting_link(@filterrific, :created_at) %></th>
    </tr>
    <% users.each do |user| %>
      <tr>
        <td><%= link_to(user.first_name, '#') %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= link_to 'Delete',  user_delete_path(user),
        data: { confirm: 'Are you sure?' }, method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= will_paginate users %>

app/views/users/edit.html.erb
<%= bootstrap_form_with(model: current_user, url: users_edit_profile_path, method: :put, local: true) do |f| %>
  <% if current_user.avatar.attached? %>
    <%= image_tag user_avatar(current_user) %>
  <% end %>
  <div class="avatar-image">
    <strong><p>This will be show avatar image</p></strong>
  </div>
  <div class="text-avatar-image">
    <strong><p>Change your avatar</p></strong>
  </div>
  <br>
  <strong><%= f.file_field name="Choose your avatar", placeholder: " Choose your avatar"%></strong>
  <strong><%= f.text_field :username, placeholder: " Enter your email" %></strong>
  <strong><%= f.text_field :first_name, placeholder: " Enter your first name" %></strong>
  <strong><%= f.text_field :last_name, placeholder: " Enter your last name" %></strong>
  <strong><%= f.text_area :about %></strong>

  <strong><%= f.select :location, [["Ukraine", 1], ["USA", 2]] %></strong></strong>
  <strong><%= f.select :language, [["eng", 1], ["rus", 2]] %></strong></strong>

  <br>
  <strong><%= f.form_group :skill_level, label: { text: "Choose your gender:" } do %></strong>
    <br>
    <div class="radio-group" id="style-radio">
      <div class='radio-button-left'>
        <strong><%= f.radio_button :skill_level, 0, label: "Male", inline: true %></strong>
      </div>
      <div class='radio-button-center'>
        <strong><%= f.radio_button :skill_level, 1, label: "Female", inline: true %></strong>
      </div>
      <div class='radio-button-right'>
        <strong><%= f.radio_button :skill_level, 2, label: "No-binary", inline: true %></strong>
      </div>
  <% end %>
  <br>
  <br>
  <div class='google-button'>
    <strong><p>Login options</p></strong>
    <strong><%= f.button name='Use your Google account to log in' %></strong>
  </div>
  <br>
  <div class='green-button'>
  <strong><%= f.button name='SAVE' %></strong>
  </div>
  <br>
<% end %>

app/views/users/index.html.erb
<h1>users</h1>
<%= form_for_filterrific @filterrific do |f| %>
  <div>
    Search
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
  <div>
    Registered after
    <%= f.text_field(:with_created_at_gte, class: 'js-datepicker') %>
  </div>
  <div>
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>
  <div>
    <%= link_to(
      'Reset filters',
      reset_filterrific_url,
    ) %>
  </div>
  <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
    Tooltip on top
  </button>
  <%= render_filterrific_spinner %>
<% end %>

<%= render(
  partial: 'users/list',
  locals: { users: @users }
) %>

app/views/users/show.html.erb
<% if @user.blocked? && can?(:activate, User) %>
  <%= link_to "Activate user!", activate_user_path(@user) , method: :post %> 
<% end %>
<% if !@user.blocked? && can?(:ban, User)%>
  <%= link_to "Ban user!", ban_user_path(@user) , method: :post %> 
<%end%> 

<%= @user.email %>
<br>
<%= link_to 'Друзья', favorites_path%>
<br>

<% if current_user.id != @user.id %>
  <% if current_user.have_favorite? @user %>
    <%= 'Вы не можете добавить этого пользователя или он уже добавлен в друзья' %>
  <% else %>
    <%= link_to 'Добавить в друзья', add_to_favorites_path(@user), method: :post %>  
  <% end %>
  <%= form_for @report, url: report_user_path(@user), method: :post do |form| %>
    <%= form.label :query, "Пожаловатся:" %>
    <br>
    <%= form.text_area :description, size: "70x5" %>
    <br>
    <%= button_to 'Сдать розбышаку в киберполицию :)', welcome_index_path %>
  <% end %>
  <% if current_user.admin? && !@user.verified%>
    <%= button_to "Confirm this account!",
                  verify_user_path(@user),
                  method: :post,
                  data:{confirm: 'User confirmated!'} %>
  <% end %>
<% end %> 