config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'welcome#index'

  get '/welcome', to: 'welcome#index', as: 'welcome_index'
  get '/favorites', to: 'favorites#show', as: 'favorites'

  delete '/favorites/:id/delete_from_favorites', to: 'favorites#destroy', as: 'delete_from_favorites'

  post '/users/:id/add_to_favorites', to: 'favorites#create', as: 'add_to_favorites'
  post '/users/:id/activate_user', to: 'users#activate', as: 'activate_user'
  post '/users/:id/ban_user', to: 'users#ban', as: 'ban_user'
  post '/users/:id/report', to: 'reports#create', as: 'report_user'
  post '/users/:id/verify_user', to: 'users#verify_user', as: 'verify_user'

  get '/users/edit_profile', to: 'users#edit', as: 'edit_profile'
  put '/users/edit_profile', to: 'users#update'
  get "/users", to: "users#index"

  get '/users/:id', to: 'users#show', as: 'user'
  delete '/users/:id', to: 'users#destroy', as: "user_delete"
  delete '/edit_profile/delete_profile', to: 'users#self_destroy', as: "user_self_destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitness</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.google.com/specimen/Open+Sans' rel='application' type='text/css' />
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <nav class="navbar navbar-expand-lg">
      <div class="navbar-nav mr-auto" id="navbarSupportedContent">
        <a class="brand-logo font-size font-weight-bold text-uppercase" href="#">
          Run<br>
          For<br>
          Fun<br>
        </a>
      </div>
      <div class="navbar-nav ml-auto mb-auto justify-content-end">
        <% if user_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-uppercase order-1 p-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              your profile
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'Edit profile', edit_profile_path, :class => 'navbar-link' %><br>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
              </div>
            </li>
            <li class="nav-item active">
              <div class="order-2 p-2">
                <%= link_to 'FAVOURITES', favorites_path, :class => 'navbar-link' %><br>
              </div>
            </li>
            <li class="nav-item active">
              <div class="order-3 p-2">
                <%= link_to "MESSAGES", edit_profile_path, :class => 'navbar-link' %><br>
              </div>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>

    <div class="page-content">
      <div class="row">
        <div class="col-md-4">
          <b-sidebar id="sidebar-right" title="Sidebar">
            <% if user_signed_in? %>
                <ul class="navbar-nav">
                  <li class="nav-item order-1 p-2">
                    <div class="order-1 p-2">
                      <%= link_to 'EDIT PROFILE', edit_profile_path, :class => 'navbar-link' %>
                    </div>
                  </li>
                  <li class="nav-item order-2 p-2">
                    <div class="order-2 p-2">
                      <%= link_to 'FAVOURITES', edit_profile_path, :class => 'navbar-link' %><br>
                    </div>
                  </li>
                  <li class="nav-item order-3 p-2">
                    <div class="order-3 p-2">
                      <%= link_to "LOGOUT", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
                    </div>
                  </li>
                </ul>
            <% end %>
          </b-sidebar>
        </div>
        <div class="bordered col-8">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>